{
 "title": "ContainerWatch - Overview",
 "refresh": "15s",
 "panels": [
  {
   "title": "Sample App Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"sample-app\"}"
    }
   ]
  },
  {
   "title": "Host CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(containerwatch_http_requests_total[1m])) by (status)"
    }
   ]
  },
  {
   "title": "Application p95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(containerwatch_http_request_duration_seconds_bucket[5m])))"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name!=\"\"}"
    }
   ]
  }
 ]
}